Aventon/auto/index.html

Acá escribir un comentario breve pero que ayude a comprender que es lo que se está subiendo

test push to origin

---

Aventon/application/controllers/register.php
Aventon/application/views/view_register.php

Add register form with basic validation (Part I)

Add register form with basic validation

---

Aventon/application/views/view_logueado.php

Mejora de codigo

---

Aventon/application/controllers/editar_perfil.php
Aventon/application/models/model_user.php
Aventon/application/views/view_editarPerfil.php

Se agrega la funcion para la modificacion de los datos personales del usuario

editar_perfil

---

Aventon/application/controllers/controller.php
Aventon/application/controllers/login.php
Aventon/application/controllers/viaje.php
Aventon/application/models/model_viaje.php
Aventon/application/views/templates/footer.php
Aventon/application/views/templates/header.php
Aventon/application/views/templates/navbar.php
Aventon/application/views/templates/sidebar.php
Aventon/application/views/viaje/view_viajes_ver.php
Aventon/application/views/view_login.php
Aventon/assets/css/template.css

cree templates, cree tabla con paginación para mostrar viajes

cree templates, cree tabla con paginación para mostrar viajes

---

Aventon/application/controllers/editar_auto.php
Aventon/application/controllers/editar_perfil.php
Aventon/application/controllers/login.php
Aventon/application/controllers/viaje.php
Aventon/application/models/model_user.php
Aventon/application/views/templates/header.php
Aventon/application/views/templates/navbar.php
Aventon/application/views/viaje/view_crear_viaje.php
Aventon/application/views/view_editar_perfil.php
Aventon/application/views/view_login.php

Actualizar información de Perfil de Usuario

Actualizar información de Perfil de Usuario

---

Aventon/application/controllers/editar_perfil.php
Aventon/application/views/templates/header-logout.php
Aventon/application/views/templates/header.php
Aventon/application/views/templates/navbar.php

Se añadio el logo de Aventon en la barra de navegacion y se realizo mejoras en el diseño

Mejora de diseño

---

Aventon/application/controllers/auto.php
Aventon/application/views/auto/view_editar_auto.php
Aventon/application/views/auto/view_info_auto.php
Aventon/application/views/auto/view_listar_autos.php
Aventon/application/views/templates/header.php

Se realizo el diseño de las vistas correspondientes al auto

Mejoras en el diseño

---

Aventon/application/views/view_register.php

Solucion a un bug

---

Aventon/application/controllers/auto.php
Aventon/application/controllers/register.php
Aventon/application/models/model_auto.php
Aventon/application/models/model_viaje.php
Aventon/application/views/auto/view_editar_auto.php
Aventon/application/views/templates/navbar.php
Aventon/application/views/view_register.php
Aventon/system/language/spanish/form_validation_lang.php

Se agrego la funcion eliminar auto y se hicieron mejoras en el codigo

Eliminar auto

---

Aventon/application/controllers/tarjeta_credito.php
Aventon/application/models/model_tarjeta.php
Aventon/application/views/templates/navbar.php
Aventon/application/views/view_registrar_tarjeta.php

Se agrego la funcion para registrar una tarjeta de credito

Registrar tarjeta de credito

---

Aventon/application/controllers/crear_viaje.php
Aventon/application/models/model_viaje.php
Aventon/application/views/viaje/view_crear_viaje.php
Aventon/system/language/spanish/form_validation_lang.php

Valida si 2 viajes se superponen, devuelve la cantidad de viajes que se superponen (si es 0, es que no se superpuso ningún viaje, sino si). Pendiente de implementar que devuelva un arreglo con la info de los viajes, para mostrar en el mensaje de error.
Refactor codigo de crear viaje, en la vista, modelo y controlador:
- se eliminaron métodos innecesarios
- se acomodo el código
- se mejoro el selector de autos en la vista

Crear viaje

---

Aventon/application/controllers/viaje.php
Aventon/application/models/model_tarjeta.php
Aventon/application/models/model_viaje.php
Aventon/application/views/viaje/view_listar_viajes.php
Aventon/application/views/viaje/view_postular_viaje.php
Aventon/application/views/viaje/view_viaje_info.php

Postularse como acompañante

---

Aventon/application/controllers/solicitud_pendiente.php
Aventon/application/models/model_solicitud.php
Aventon/application/models/model_tarjeta.php
Aventon/application/models/model_viaje.php
Aventon/application/views/solicitud/view_solicitud_pendiente.php
Aventon/application/views/templates/navbar.php
Aventon/system/language/spanish/form_validation_lang.php

Se creo el Listado de solicitudes pendientes, con 2 links de Aceptar y Rechazar. En caso de no haber creado ningún viaje redirige al Listado de viajes con un mensaje de error 'No tiene ninguna solicitud ya que no ha creado ningún viaje'.

Se creo el Listado de solicitudes pendientes

---

Aventon/application/controllers/crear_viaje.php
Aventon/application/models/model_viaje.php
Aventon/application/views/viaje/view_crear_viaje.php

Ya se puede crear un viaje único, o con frequencia diaria o semanal. Y valida la superposición.

Se agrego el crear viaje diario, y validación de superposición para viajes múltiples.

---

Aventon/application/controllers/viaje.php
Aventon/application/models/model_viaje.php

Se eliminan todas las solicitudes que se realizaron al viaje eliminado, ya se aceptado, pendiente, rechazado o inactivo

Eliminar viaje

---

Aventon/application/models/model_viaje.php
Aventon/application/views/viaje/view_crear_viaje.php

Se ocultan campos de acuerdo al check de frequencia chequeado, en el form de Crear Viaje.
Lista solo viajes cuya fecha >= fecha actual y estado=0

Crear viaje oculta campos de acuerdo a frequencia, y listas viajes fecha >= fecha actual

---

Aventon/application/controllers/tarjeta_credito.php
Aventon/application/views/tarjeta_credito/view_registrar_tarjeta.php
Aventon/system/language/spanish/form_validation_lang.php

Se agregaron las validaciones PHP y JS en el input fecha

Registrar Tarjeta de Credito. 

---

Aventon/application/models/model_auto.php
Aventon/application/models/model_viaje.php

Eliminar auto. Eliminar viaje. 

---

Aventon/application/controllers/viaje.php
Aventon/application/views/viaje/view_listar_viajes.php

Muestra cantidad de viajes existentes (cuando no se realizó búsqueda) y cantidad de viajes que coinciden con los criterios de búsqueda.

Muestra cantidad de resultados

---

Aventon/application/controllers/viaje.php
Aventon/application/views/templates/navbar.php
Aventon/application/views/viaje/view_listar_viajes.php
Aventon/system/language/spanish/form_validation_lang.php

Cambio de expresión regular para permitir búsqueda por números, por ejemplo: 25 de Mayo. Fix del problema que mantiene los datos de búsqueda cuando se navega a otra página.

Cambio de expresión regular en búsqueda, y fix de un bug.

---

Aventon/application/controllers/crear_viaje.php
Aventon/application/controllers/viaje.php
Aventon/application/views/viaje/view_crear_viaje.php
Aventon/application/views/viaje/view_editar_viaje.php
Aventon/system/language/spanish/form_validation_lang.php

Correcciones de bugs. Se modifico la creación y edición para que permita números en orígen y destino (por ejemplo 25 de Mayo, 9 de Julio), se cambio expresión regular en crear y editar viaje, se agrego validación de destino diferente a origen.

Correcciones de bugs. Mejoras en crear y editar viaje.

---

Aventon/application/controllers/editar_perfil.php
Aventon/application/models/model_user.php
Aventon/application/views/tarjeta_credito/view_editar_tarjeta.php
Aventon/application/views/tarjeta_credito/view_registrar_tarjeta.php
Aventon/application/views/view_editar_perfil.php

Se soluciono el bug donde se perdia la sesion al entrar a dicha seccion

Editar perfil. 
